### ISSUE TITLE
Repo - Structure as Unity UPM-compatible Package

### ISSUE THREAD

**Issue by SamuelAsherRivello** [trilitech/tezos-unity-sdk#10]
The repo is currently structured as a Unity Project. ([link](https://www.google.com/search?q=what+is+a+unity+project&oq=what+is+a+uni&aqs=chrome.0.69i59j69i57j0i512l4j69i61j69i60.1473j0j7&sourceid=chrome&ie=UTF-8))

To improve integration with user's new and existing Unity Projects, I suggest...

**Suggestion**
1. The repo be structured instead as a Unity UPM-compatible Package ([link](https://docs.unity3d.com/Manual/CustomPackages.html))

**Optional Additions**

* I moved this to its own ticket - The resulting package be published to NPMJS - https://github.com/trilitech/tezos-unity-sdk/issues/23

NOTE: This request does not directly relate to any current or future release of the Tezos Unity SDK on the ASSET STORE. That is a separate subject matter. 

TAG
#PriorityForSam

**Comment by SamuelAsherRivello** [comment]
Someone, perhaps Jeremy, in Slack mentioned https://solana.unity-sdk.gg/ . I gave it a look. It's a good inspiration for web docs, installation of SDK, and good separation of any samples from the SDK.

Here is a video of me talking about it. https://tezos-dev.slack.com/archives/C04JEV96Q2H/p1678096701803079

Enjoy!

**Comment by k-karuna** [comment]
Closed with #25
