### ISSUE TITLE
Separate SDK Concerns from "Demo Example" Concerns

### ISSUE THREAD

**Issue by SamuelAsherRivello** [trilitech/tezos-unity-sdk#11]
The repo contains a Unity Project.

In the Assets Folder, there are folders and files that relate to 2 concerns...

**Concerns**
1. SDK
2. Demo Example and related files

![image](https://user-images.githubusercontent.com/63511769/222165436-3394981b-3915-4ed9-aee3-cfeab4c389d4.png)

**Suggestion**
* Separate (e.g. remove) the "Demo Example.unity" Scene and all related files. This will indicate to users who want to bring the SDK functionality into production which files are needed (e.g. SDK) and which files are not (e.g. Demo Example)

**Solution Paths** to Suggestion, Either
1. If https://github.com/trilitech/tezos-unity-sdk/issues/10 is accepted, completed, and merged beforehand (**recommended**). Then the "Demo Example.unity" and its related files are to be moved to the "Samples~" of the Unity UPM-Compatible Package Structure ([link](https://docs.unity3d.com/Manual/cus-layout.html))
2. Otherwise, make sibling folders within /assets/ to clearly separate the 2 concerns. Such that users can delete the examples without compilation errors.

NOTE: Currently any/all prefabs related to the "QR code functionality" are within "DemoExample". Separately I'll suggest how to address that.

TAG
#PriorityForSam

**Comment by SamuelAsherRivello** [comment]
Someone, perhaps Jeremy, in Slack mentioned https://solana.unity-sdk.gg/ . I gave it a look. It's a good inspiration for web docs, installation of SDK, and good separation of any samples from the SDK.

Here is a video of me talking about it. https://tezos-dev.slack.com/archives/C04JEV96Q2H/p1678096701803079

Enjoy!

**Comment by SamuelAsherRivello** [comment]
Here is some anecdotal observations in the code that may help this task.

* Consider updating `Tezos.cs` to be the single entry point per https://github.com/trilitech/tezos-unity-sdk/issues/17 
* Consider moving some functionality from `ExampleManager.cs` to `Tezos.cs`, including 'which user is logged in'

**Comment by k-karuna** [comment]
Closed with #25
