### ISSUE TITLE
WebGL staging during development [question]

### ISSUE THREAD

**Issue by AlexandrosGounis** [trilitech/tezos-unity-sdk#117]
If this is not the right place please close this issue.

Suppose we want to touch `typescript` in the Demo Example. Our understanding is that we have to copy & paste the `output` (WebGL related) folders manually, which are then cached within `Library/PackageCache`. Each time we have to make a change, we have to create a new build (with WebGL as the target), and run that locally.

What would the ideal development flow be? This includes touching `.ts` files, and/or `.cs` files. 

Our view is that this kind of development can be very slow and inefficient and we would like to explore more options on how to improve web/typescript integration and the development experience for those who want to work with Tezos Unity SDK & WebGL builds

**Comment by k-karuna** [comment]
Hi @AlexandrosGounis. 
You are going to add some improvements for SDK?

All interactions between `.cs` code and `.js` bundle happens through [BeaconConnectorWebGL](https://github.com/trilitech/tezos-unity-sdk/blob/main/Runtime/Scripts/Beacon/BeaconConnectorWebGl.cs)
So, all you need is to pass correct data to input and correct handle output for all method of `IBeaconConnector`
During developing in `.ts` files you should always run `npm run build` to create relevant bundle.

When you click Build and run button in Unity editor, it will suggest you to choose directory where to store static files, so you can setup your [webpack config](https://github.com/trilitech/tezos-unity-sdk/blob/0fb40ac39f8448692935447b68b76c4f3be61d35/WebGLFrontend/webpack.config.js#L23) to save output file in this directory to update `.js` bundle. Thereby you can refresh you runnng WebGL localhost after `npm run build` to run relevant `.js` code.

**Comment by cnbrk13** [comment]
Closing this, feel free to create a new one if you have further problems/questions.
