### ISSUE TITLE
Add Authentication.prefab to SDK

### ISSUE THREAD

**Issue by SamuelAsherRivello** [trilitech/tezos-unity-sdk#12]
Authentication is a popular use case of Web3. So popular I suggest it be solved at the SDK level.

**Current**

The repo contains a "Demo Example. unity" scene that shows authentication. That's great.

See image. 
1. The included scene
2. shows the QR code
3. Which is part of a functional, demo-only prefab 

![image](https://user-images.githubusercontent.com/63511769/222183403-28c0346c-0c64-48dc-816e-cc4ce8b34ec4.png)

There are **many** ways to solve it well. May the following be inspiration for those assigned. I recommend to address the optional prerequisites first to provide a foundation for the suggestion below.

**Prerequisites**
* https://github.com/trilitech/tezos-unity-sdk/issues/10
* https://github.com/trilitech/tezos-unity-sdk/issues/11 

**Suggestion**
* Create an `Authentication.prefab` and include it in the SDK. It includes a Unity Canvas and the components scripts within for a generalized authentication solution meant for production. 

**Scoping**
* Meeting all use-cases is unrealistic. Some users will have custom needs. Due diligence in planning can include a modest set of common production needs. For example, **do** include a light C# api to call things like `Connect()`, `Disconnect()` and `OnAuthenticationStateChanged.AddEventListener()`, yet **do not** offer custom customization of any visual elements like the color of the QR image. 

**Definition of Done**

Something like this.

1. User creates a new Unity Project
4. User imports SDK through Unity Package Manager
5. User creates a new scene
6. User drags the `Authentication.prefab` from /Packages/Blah/Foo/ to the Unity Scene Hierarchy. This does not render in the Scene View (e.g. visual elements are not enabled)
7. User selects the `Authentication.prefab` instance in the scene and modifies the custom properties. (e.g. Set "WillConnectOnAwake=true")
8. User plays the scene
9. `Authentication.prefab` instance connects upon Awake
10. `Authentication.prefab` instance is now visible
11. User sees the QR code shown centered onscreen
12. User captures QR code with compatible wallet (this functionality already exists). The user is now authenticated
13. `Authentication.prefab` instance is now **not** visible

TAG
#PriorityForSam

**Comment by SamuelAsherRivello** [comment]
Further thoughts on this ticket added here in video
https://tezos-dev.slack.com/archives/C04UQ4BGBKL/p1679910997172939?thread_ts=1679908644.515139&cid=C04UQ4BGBKL

**Comment by mismirnov** [comment]
@SamuelAsherRivello What about logout? If the user is authenticated, he will not be able to repeat this.

**Comment by efetez** [comment]
@mismirnov I agree with you here. Logout is an essential function of this process. 

With my limited knowledge, I'd suggest extending the existing C# API by adding a `Logout()`  _(or `Disconnect() `as Sam mentioned above)_ method, which would log the user out and clear any saved authentication data.

To provide user control, we can add a customizable "Log Out" button to the `Authentication.prefab` which would be visible when/after the user is authenticated. This button can trigger the `Logout()` method when clicked. We can place it in the right corner of the UI (speaking from the example image that Sam sent)

After a successful logout, the `Authentication.prefab` instance can return to its initial state, displaying the QR code for the user to log in again if desired.
