### ISSUE TITLE
Add Cross-Session-Persistence to Authentication

### ISSUE THREAD

**Issue by SamuelAsherRivello** [trilitech/tezos-unity-sdk#13]
Authentication is a popular use case of Web3. 

**Current**

The repo contains a "Demo Example. unity" scene that shows authentication. That's great.

See image. 
1. The included scene
2. shows the QR code
3. Which is part of a functional, demo-only prefab 

![image](https://user-images.githubusercontent.com/63511769/222183403-28c0346c-0c64-48dc-816e-cc4ce8b34ec4.png)

**Current UX**
1. Open "Example Demo.unity" Scene
2. Play Scene
3. UI shows QR code indicating the user is not authenticated
4. User authenticates (e.g. With QR code and mobile wallet)
5. Runtime UI shows "Welcome" indicating user is authenticated
6. Stop Scene
7. Play Scene
8. UI shows QR code indicating the user is not authenticated **This is the issue**

I assume there is zero cross-session-persistence to the authentication. This limits the end-player experience using apps built on top of the SDK. This also limits the quality of life for developers working on top of the SDK. The current requirement to auth every time a developer hits play is a time-sink.

**Suggestion**
* Allow the authenticated user to stay authenticated between game sessions (e.g. stop/start scene) , unity sessions (e.g. close/open unity editor), etc...

**Suggested UX**
1. Open "Example Demo.unity" Scene
2. Play Scene
3. UI shows QR code indicating the user is not authenticated
4. User authenticates (e.g. With QR code and mobile wallet)
5. Runtime UI shows "Welcome" indicating user is authenticated
6. Stop Scene
7. Play Scene
8. Runtime UI shows "Welcome" indicating user is authenticated. **This is a definition of done**.

Ideally the session persists as long as is feasible per any security concerns (e.g. days/weeks) 

Ideally, the SDK supports an API to disconnect/end the authenticated session (e.g. User clicks a logout button). This is a must-have feature.

### Workaround

Before this task is fully complete, a hacky workaround that would help user-devs would be to add functionality to the API to hardcode an authenticated web3 address and thus bypass the need to auth.

**Pseudocode**

```
if (isWorkaround)
{
     //Fake auth. Or perhaps there is a legit long-term use case of this API
     FakeTezosSDK.blah.FakeAuthWithAddress ("0x123...ABC");
}
else
{
    // Do full auth with QR code
}

// Full API is ready for use

```

TAG
#PriorityForSam

**Comment by k-karuna** [comment]
Closed with #25
