### ISSUE TITLE
Demo QR Authentication Process is Unstable

### ISSUE THREAD

**Issue by SamuelAsherRivello** [trilitech/tezos-unity-sdk#14]
Authentication is a popular use case of Web3.

The repo contains a "Demo Example. unity" scene that shows authentication. That's great.

Sometimes it works. 

Sometimes it doesn't. Here is info on failing scenarios with both **Temple Wallet** and **Umami Wallet**.

# Trial Scenario 1 - With Temple Wallet

**Test Scenario**

* SDK Version: https://github.com/trilitech/tezos-unity-sdk/commit/fc3eaf5513e4755ea1ba7275860b35b00eeb7e37
* Unity Version: 2021 Latest LTS
* Unity Editor Platform: Windows
* Unity Target Platform: WindowStandalone
* Mobile Wallet: Temple Wallet on Android 
## Expected User Experience

1. Open "Example Demo.unity" Scene
2. Play Scene
3. Scan QR With Mobile
4. Mobile Wallet: Scan Unity QR 
5. Mobile: Success
6. Unity UI shows ‘Welcome”. This is the key sign of success.
7. Stop Scene

## Actual User Experience

**Sometimes** it succeeds per EXPECTED RESULTS above. Sometimes it fails per either of the 2 ways below.

**Failure Type # 1**

1. Open "Example Demo.unity" Scene
2. Play Scene
3. Scan QR With Mobile
4. Mobile Wallet: Scan Unity QR 
5. Mobile: Success
6. Mobile: Failure. Hangs forever (e.g. 15 seconds, then I choose to close the app)
7. Stop Scene

<img width="200" src="https://user-images.githubusercontent.com/63511769/222444214-9b7dc4fe-9f3f-47e8-98bc-e62ad3b7af01.png" />

**Failure Type # 2**

1. Open "Example Demo.unity" Scene
2. Play Scene
3. Scan QR With Mobile
4. Mobile Wallet: Scan Unity QR 
5. Mobile: Success
6. Mobile: Failure. Shows Invalid code
7. Stop Scene

<img width="200" src="https://user-images.githubusercontent.com/63511769/222444255-64c4d8c8-ff2d-4a0c-8fab-1906bdae27ce.png" />

**Workarounds:** All testing is done without any workarounds. No workarounds have been discovered for temple wallet.

# Trial Scenario 2 - With Umami Wallet

**Test Scenario**

* SDK Version: https://github.com/trilitech/tezos-unity-sdk/commit/fc3eaf5513e4755ea1ba7275860b35b00eeb7e37
* Unity Version: 2021 Latest LTS
* Unity Editor Platform: Windows
* Unity Target Platform: WindowStandalone
* Mobile Wallet: Umami Wallet on Android 

## Expected User Experience

1. Open Scene
2. Play Scene
3. Scan QR With Mobile
4. Mobile Wallet: Scan Unity QR 
5. Mobile: vibrates when detecting the QR
6. Mobile: Shows “Confirm?” User click yes
7. Mobile: Success
8. Unity UI shows ‘Welcome”. This is the sign of success.
9. Stop Scene

## Actual User Experience

**Sometimes** it succeeds per EXPECTED RESULTS above. Sometimes it fails per below.

**Failure Type # 3**

1. Open Scene
2. Play Scene
3. Scan QR With Mobile
4. Mobile Wallet: Scan Unity QR 
5. Mobile: vibrates when detecting the QR. Good.
6. Mobile: shows the 0 dapps or 1 dapps image without showing any “Confirm?”
7. Unity UI continues to show the QR code 
8. Stop Scene

**Images**

NOTE: Neither image necessarily indicates a failure. But if we start with 0 dapps, and you register and it fails, the result will still show 0 dapps. And if we start with 1 dapps, and you register and it fails, the result will still show 1 dapps.

With No Dapps 

<img width="200" src="https://user-images.githubusercontent.com/63511769/222461275-1691ae90-2dbe-4f4b-bc65-c0e4d6bfde89.jpg" />

With One Dapps 

<img width="200" src="https://user-images.githubusercontent.com/63511769/222459275-d2c237a1-52dd-4945-bcdb-b8497db1264f.jpg" />

**Workarounds:** All testing is done without any workarounds. However, a short-term workaround with Umami I found is to remove all registered 'dapps' within the mobile wallet before each attempt at authentication.

TAG
#PriorityForSam

**Comment by k-karuna** [comment]
Seems that it works now stable, closed with #25

**Comment by fraidev** [comment]
I am having the same issue with QR Code on macOS using Temple on IOS and directly on IOS apps too.

**Comment by m-kus** [comment]
@fraidev can you please try to increase the QR code size and try again?
Also if you could test using other mobile wallets to confirm it's not Temple related (we had similar issues with Temple before while everything was ok with other wallets).
We observe inconsistent behavior in QR code scanning on different devices/screen types
