### ISSUE TITLE
Add a higher-level API for reading data from FA2 contracts

### ISSUE THREAD

**Issue by mathias-hiron** [trilitech/tezos-unity-sdk#15]
The SDK currently provides a low level API on top of which a lot can be built, with some effort.

To make things easier for most devs, key use cases should be supported directly by the SDK using a higher-level API.

One such important use case, is accessing the list of tokens of a given user address in a given FA2 contract, along with their metadata. This would be an API that handles aspects of [tzip-12 (FA2)](https://tzip.tezosagora.org/proposal/tzip-12/), [tzip-16 (Contract metadata)](https://tzip.tezosagora.org/proposal/tzip-16/) and [tzip-21 (Rich Metadata)](https://tzip.tezosagora.org/proposal/tzip-21/).

A very first version of the API would support just enough to interact with the contracts created by the Objkt's minting Factory. Here is an example of such contract: KT1AXCXcYiV1ACc6diBfHq1TVynj8KvqeoUZ

The API would make it possible to:
- obtain the list of tokens that a given user owns on such a contract
- obtain metadata such as the values the image, tags and attributes from each of these tokens.

Fetching these can be done through tzkt, with a query like this:
https://api.tzkt.io/v1/tokens/balances?token.contract=KT1AXCXcYiV1ACc6diBfHq1TVynj8KvqeoUZ&account=tz1ZuhCMnA1gZHfNzgKNFm1B2mjSDKJsQfJN

Performance issues need to be taken into account, to avoid putting unnecessary load on tzkt. In the initial use case, the intent is not for the game to get real time updates on these, but maybe load them at startup or when the user explicitly requests to refresh the data. For real time updates, a system of events would later need to be added.

Support for pagination and filtering / requesting only a subset of the fields could be a good idea to improve performance, but a version without it would already be great.

**Comment by zamrokk** [comment]
`avoid putting unnecessary load on tzkt`

Why ? Goal of an indexer is to be enough robust to support any request like Google does

- With doing an unique call at startup/caching would decrease workload   
- I doubt we will have heavy volume right now, btw


"Objkt's minting Factory"  <= so first version would be to mint all NFT manually on Objkt ?

**Comment by Groxan** [comment]
> > avoid putting unnecessary load on tzkt
>
> Why ? Goal of an indexer is to be enough robust to support any request like Google does

That's not the goal of the indexer. The goal is to provide you with flexible access to the blockchain data. Robustness is an absolutely different thing, that directly depends on the resources you are willing to spend. So, let's be more responsible, because the less efficient code you write, the greater someone's expenses ;)

> like Google does

Interesting expectations 😄 Do you realize how much resources Google spends to handle the load?

**Comment by Groxan** [comment]
Right. Nevertheless, I don't think customers will be happy, paying for actually unnecessary things. Like, for example, paying for 100k requests per day, while it could be 10k, if you spent some time on optimization :)

**Comment by mathias-hiron** [comment]
> `Objkt's minting Factory` <= so first version would be to mint all NFT manually on Objkt ?

The current plan is to use DNS, as you can provide more information and do batch mint of NFTs

In the future, we could allow minting from the game or from the unity Editor

**Comment by m-kus** [comment]
Specification (RFC): https://hackmd.io/zaZTTOe1R4uz6HwghUVBaw
