### ISSUE TITLE
'Newtonsoft' could not be found in macOS

### ISSUE THREAD

**Issue by newyellow** [trilitech/tezos-unity-sdk#20]
This error message appears and could not play:

Assets/TezosUnitySDK/Scripts/BeaconSDK/BeaconConnectorDotNet.cs(17,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

Tested with a clean project with just TezosSDK 1.0 intalled.
Also try replacing Scripts with the current repo, but still not working.

Unity Version: 2021.3.20f1
macOS Version: 13.2.1

<img width="752" alt="Screenshot 2023-03-09 at 3 10 47 PM" src="https://user-images.githubusercontent.com/8190143/223947292-38c43ffa-f0de-48b3-8f4f-647ac1195541.png">
<img width="1384" alt="Screenshot 2023-03-09 at 3 10 38 PM" src="https://user-images.githubusercontent.com/8190143/223947304-9d9cc0e9-eb68-4edb-8414-e496bd658e42.png">

**Comment by k-karuna** [comment]
Do I understand correctly that you created clean project and added this SDK by dragging it inside you project?

**Comment by k-karuna** [comment]
Regarding to our docs https://opentezos.com/gaming/unity-sdk/getting-started/#add-newtonsoft-package-if-needed
now you need to install Newtonsoft manually, unitl we transform this SDK to UPM package.

**Comment by newyellow** [comment]
@k-karuna I use version 1.0 via UnityAssetStore which is usually Unity users finds plugins.
It frustrates users if a direct import from AssetStore is not working.
https://assetstore.unity.com/packages/decentralization/infrastructure/tezos-sdk-for-unity-239001

And thank you for the doc referral, will give it a try!
