### ISSUE TITLE
Repo - Publish To NPMJS

### ISSUE THREAD

**Issue by SamuelAsherRivello** [trilitech/tezos-unity-sdk#23]
After this one

* https://github.com/trilitech/tezos-unity-sdk/issues/10

Then do

* Published the repo package to some package registry. A popular one is NPMJS. Info and benefits are here ([link](https://forum.unity.com/threads/publish-unity-package-with-npmjs.882010/))

**Comment by k-karuna** [comment]
Closed with #25
