### ISSUE TITLE
The type 'JObject' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by m-kus** [trilitech/tezos-unity-sdk#32]
I followed the instructions to use the sdk in unity (on opentezos), I import the Tezos SDK package and also the Newtonsoft package because I use a recent version of unity.
Then i have this error:  Assets\tezos-unity-sdk-main\Runtime\Scripts\BeaconSDK\BeaconConnectorDotNet.cs(150,56): error CS0012: The type 'JObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'Newtonsoft.Json.

Temporary workaround: https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Install-official-via-UPM

**Comment by k-karuna** [comment]
Fixed in #34
