### ISSUE TITLE
Tutorial go mint NFTs on Ghostnet

### ISSUE THREAD

**Issue by mathias-hiron** [trilitech/tezos-unity-sdk#45]
As Objkt or DNS don't have a version on ghostnet, we need to prepare a tutorial that shows how to do it.

An initial version was created that uses octez-client. We will do one that uses the BCD, starting from https://better-call.dev/deploy

**Comment by mathias-hiron** [comment]
I prepared a draft here:

https://docs.google.com/document/d/1TapdETfiwqMq3WWcNr88Von8NbkxvZe0uqnoW-F7Kb8/edit?usp=sharing

It uses the "Fork" feature of BCD. I provided a direct link, but also explained how to obtain it.

**Comment by efetez** [comment]
This will be included in the Example & Tutorial scenes. Closing for now as it will be tracked.
