### ISSUE TITLE
Error: Sharing violation on beacon.db

### ISSUE THREAD

**Issue by m-kus** [trilitech/tezos-unity-sdk#47]
OS: Windows 10
Unity version: 2021.3.23f1
Unity SDK version: 1.3.0
Target platform: Windows Standalone

Steps to reproduce:
- Create new project
- Import Unity SDK via UPM
- Drag AuthenticationQr.prefab into an empty scene
- Press play

Sometimes it works, sometimes it fails.

Error: 
`IOException: Sharing violation on path C:\Users\xxx\AppData\LocalLow\Tezos\Examples Project\beacon.db`
![image](https://user-images.githubusercontent.com/44951260/234647320-8b8af40f-4430-4c26-b94c-047a95166124.png)

Workaround:
If close and open the Unity editor it works well once afterwards

Hint:
Most likely the c# code leaves a file open somethimes, but it should never do so.

**Comment by m-kus** [comment]
Need to bump beacon dependency: https://github.com/baking-bad/beacon-dotnet-sdk/releases/tag/v1.0.23

**Comment by m-kus** [comment]
Still reproduces on 1.3.1

```
We have issue at the QR generation as upon the first generation, we get an ioexception, violation of 
shared path error for the beacon.db and beacon-log.db file generated. We tried moving it to a different   
directory, the same error will still occur. Our current work around is to delete and regenerate the files, 
however this will sever the existing wallet connection and treat it as a new connection.

This error will not trigger with a fresh project.
```

**Comment by k-karuna** [comment]
This issue appears on old .db files, we have updated [beacon-dotnet-sdk](https://github.com/baking-bad/beacon-dotnet-sdk) dependency that have updated litedb version within itself. We should to improve beacon-dotnet-sdk to handle this cases e.g. by migrations, but until it is done workaround is to use new database file, e.g. you can use new db filename in [beacon options](https://github.com/trilitech/tezos-unity-sdk/blob/2f1e85cacaaca957759f9bb44d220a7bf0d1b60f/Runtime/Scripts/Beacon/BeaconConnectorDotNet.cs#L37)
