### ISSUE TITLE
DontDestroyOnLoad only work for root GameObjects error

### ISSUE THREAD

**Issue by m-kus** [trilitech/tezos-unity-sdk#50]
Either Authentication or MainThreadExecutor prefabs introduces a warning
![image](https://user-images.githubusercontent.com/44951260/234649613-be2e6edf-6f4a-4c91-ba8d-1e563c018b7b.png)

Related https://forum.unity.com/threads/singleton-dontdestroyonload-only-work-for-root-gameobjects-error.485875/

**Comment by fraidev** [comment]
I can't replicate this warning, is this still happening?
