### ISSUE TITLE
Multiple 'X type conflicts with the imported type' warnings

### ISSUE THREAD

**Issue by m-kus** [trilitech/tezos-unity-sdk#51]
![image](https://user-images.githubusercontent.com/44951260/234652067-db6db6ae-7eb4-45ab-a09d-4a1b8a86fdac.png)

Hint:
![image](https://user-images.githubusercontent.com/44951260/234652174-0d638df1-3d33-4cc3-95b6-fc4e4d52535c.png)

Related: https://answers.unity.com/questions/1439537/warning-type-conflicts-with-the-imported-type.html

**Comment by fraidev** [comment]
I think that https://github.com/trilitech/tezos-unity-sdk/pull/58 resolved this issue.

**Comment by k-karuna** [comment]
Resolved in #33
