### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by KevDevMan** [trilitech/tezos-unity-sdk#68]
SDK 1.4.0
Unity 2021.3.23f1

Game of 3 scences
Home scene i have a script behind with the following

_NOTE: I was using your singleton patteren (Which was not working, same error) but moved code._ 

```
private ITezos _tezos;

void Start()
{
        _tezos = TezosSingleton.Instance;
        _tezos.Wallet.MessageReceiver.AccountConnected += OnAccountConnected;
        _tezos.Wallet.MessageReceiver.AccountDisconnected += OnAccountDisconnected;
}

public void ConnectWallet()
    {
        _tezos.Wallet.Connect();
    }

    private void OnAccountConnected(string account)
    {
        
        if (!string.IsNullOrEmpty(account))
        {
            welcomeText.text = _tezos.Wallet.GetActiveAddress();
        }
    }
```

When this screen first loads, i am able to connect and disconnect as the MessageReciever events are firing.

When i return to Home scene, 
_tezos.Wallet.GetActiveAddress() is set correctly
but none of the MessageReciever events are getting fired

In Chrome  DevTools i am seeing this error when i try to "Connect" again. (Temple, opens and i log in etc and confirm but then nothing.)

`SendMessage: object UnityBeacon not found!`

**Comment by k-karuna** [comment]
@KevDevMan this issue related to WebGl platform, right?
Did you activate [WebGl tools](https://github.com/trilitech/tezos-unity-sdk/blob/main/WebGLSupport.unitypackage) before building? And also you need to use Airgap template in Project settings -> Player -> Web tab -> Resolution and presentation

**Comment by k-karuna** [comment]
@KevDevMan Fix in main branch, you can check out to latest commit to test.

**Comment by KevDevMan** [comment]
Yep,webGL,
Using airgap template
Activate webgl Tools? Is that in the set up instructions?

Kevin
