### ISSUE TITLE
Marketplace is not getting loaded on WebGL

### ISSUE THREAD

**Issue by umutkutlu** [trilitech/tezos-unity-sdk#88]
### Definition
Marketplace is not getting loaded on WebGL.

![WebGLMarketPanelStuck](https://github.com/trilitech/tezos-unity-sdk/assets/33513682/51196e80-64d7-4e39-87ba-b17cd8be0975)
## Steps To Reproduce

1. Create a new unity project
2. Import the sdk from package manager
3. Install the sample
4. Go to `WebGLFrontend/output` and copy the `StreamingAssets` and `WebGLTemplates` folders. Navigate to the `Assets` folder and paste copied folders.
5. Switch platform to WebGL
6. Uncheck `Auto Graphics API` from `ProjectSettings/Player/Other Settings`
7. Choose `Airgap` WebGL Template from `ProjectSettings/Player/Resolution and Presentation`
8. Build the project to WebGL
9. Connect your wallet
10. Click `MARKET` button to load Market Panel

### Possible Solution

- [x] #89

**Comment by k-karuna** [comment]
@umutkutlu what SDK and Unity versions did you tried?

**Comment by umutkutlu** [comment]
> @umutkutlu what SDK and Unity versions did you tried?

**Unity Version:** 2021.3.23f1
**SDK Version:** 1.4.0 and [latest](https://github.com/trilitech/tezos-unity-sdk/commit/d4af39461176781a85c9796dce2ddd0ceeda4ae5) (unreleased)
